services:
  postgres:
    image: postgres:16
    shm_size: 128mb
    container_name: chatuapp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2025"
      POSTGRES_DB: ChatUapp
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "ChatUapp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: chatuapp-postgres-adminer
    restart: always
    ports:
      - "9090:9090"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    command: ["php","-S","0.0.0.0:9090","-t","/var/www/html"]

  migrator:
    build:
      context: .
      dockerfile: src/ChatUapp.DbMigrator/Dockerfile
    container_name: chatuapp-migrator
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # ✅ use map form + quotes + semicolon before SSL Mode
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=ChatUapp;Username=postgres;Password=2025;SSL Mode=Disable"
      OpenIddict__Applications__ChatUapp_App__ClientId: ChatUapp_App
      OpenIddict__Applications__ChatUapp_Swagger__ClientId: ChatUapp_Swagger
      OpenIddict__Applications__ChatUapp_Swagger__RootUrl: "http://localhost:44360/"
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

volumes:
  pg-data:
